---
# tasks file for superset

- name: Installing dependencies for superset
  package:
    name: "{{item}}"
    state: present
  with_items:
    - "build-essential"
    - "libssl-dev"
    - "libffi-dev"
    - "python-dev"
    - "python-pip"
    - "libsasl2-dev"
    - "libldap2-dev"

- name: Installing pip dependencies for superset
  pip:
    name: "{{item}}"
  with_items:
    - "virtualenv"
    - "setuptools"

- name: Upgrading pip dependencies for superset
  pip:
    name: "{{item}}"
    extra_args: --upgrade
  with_items:
    - "pip"
    - "setuptools"