---
# tasks file for superset

- name: Installing system dependencies for superset
  package:
    name: "{{item}}"
    state: present
  with_items:
    - "build-essential"
    - "libssl-dev"
    - "libffi-dev"
    - "python-dev"
    - "python-pip"
    - "libsasl2-dev"
    - "libldap2-dev"
  tags:
    - system_dependencies

- name: Installing pip dependencies on the system
  pip:
    name: "{{ item }}"
  with_items:
    - "virtualenv"
    - "setuptools"

- name: Create virtual env with pip dependencies for superset
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{superset_env}}"
    virtualenv_command: virtualenv
  with_items:
    - "setuptools"
    - "pip"
    - "superset"

- name: Upgrading pip dependencies for superset
  pip:
    name: "{{item}}"
    virtualenv: "{{superset_env}}"
    extra_args: --upgrade
  with_items:
    - "pip"
    - "setuptools"